### ISSUE TITLE
Improve lock-file handling

### ISSUE THREAD

**Issue by dev-zero** [stepping-stone/sepiola#11]
The current lock-file handling to ensure only one Sepiola-instance/user is flawed.
One of the problem is that Sepiola only checks for the PID specified in the lock-file but not for the name of the application belong to that PID. This means that if different process is running with the same PID as Sepiola when it was running before, the user will get the error "Application is already running" even if it isn't.

**Comment by dev-zero** [comment]
When using the application name, make sure to remember the white-labeling and don't harcode the application name.

**Comment by philippoehler** [comment]
It looks like `QSharedMemory` is the way how to implement this behaviour.

 http://aeguana.com/blog/how-to-run-a-single-app-instance-in-qt/

**Comment by dev-zero** [comment]
well, we don't want a single instance per-machine, only per-user.
But using the user id/name as part of the `<unique identifier 2>` could probably solve that.

**Comment by philippoehler** [comment]
It looks like QShardMemory::lock() is exactly what we need to protect the shard memory segment.
`QSharedMemory provides access to a shared memory segment by multiple threads and processes. It also provides a way for a single thread or process to lock the memory for exclusive access.`
From the Qt 4.8 documentation:
(http://doc.qt.io/qt-4.8/qsharedmemory.html)

There is no need for an additional semaphore, as long as we pass the key to the constructor.
`When using native keys, shared memory is not protected against multiple accesses on it (e.g. unable to lock()) and a user-defined mechanism should be used to achieve a such protection.`
From the Qt 4.8 documentation:
(http://doc.qt.io/qt-4.8/qsharedmemory.html)

**Comment by dev-zero** [comment]
confirmed to be fixed in 2.5.0.rc0 by code-reviewe
