### ISSUE TITLE
Handle big files

### ISSUE THREAD

**Issue by patklaey** [stepping-stone/sepiola#23]
It is currently not possible to backup files bigger than 4GiB. The rsync process cannot allocate more than 4GiB of memory and crashes what eventually leads to a crash of the whole backup client.

**Comment by dev-zero** [comment]
Ok, update to latest rsync version solves this. The rsync-update for Linux is tracked in #75.
This was successfully tested with a 6GB file on Windows 7 and latest Cygwin-rsync.
