### ISSUE TITLE
Restore to original location under windows restores files to C:

### ISSUE THREAD

**Issue by patklaey** [stepping-stone/sepiola#24]
When restoring a backup to original location, the drive letters were not (correctly) considered. The file E:\some\path\to\file.txt was not downloaded to E:\some\path\to\ (even if the log file says "Downloading E:\some\path\to\file.txt") but to C:\E\some\path\to\file.txt (see attached screenshot).
![image001](https://f.cloud.github.com/assets/2681963/2469662/560204ac-b002-11e3-887a-ceab9db5f355.png)
Finally the restore process fails with the error message: 

ERROR: Writing SD to <\?\E:\some\path\to\file.txt> failed with: Das System kann die angegebene Datei nicht finden.

**Comment by paescuj** [comment]
Seems to be fixed, tested with [v2.7.1](../releases/tag/v2.7.1).
