### ISSUE TITLE
Windows-Installer installs Sepiola into versioned directory

### ISSUE THREAD

**Issue by dev-zero** [stepping-stone/sepiola#37]
... this is simply wrong. It should always use an unversioned directory.

**Comment by dev-zero** [comment]
... the same goes for the registry directory where the de-install information is stored.

**Comment by dev-zero** [comment]
The reason for this is most likely [CPack Example](http://www.cmake.org/Wiki/CMake:Packaging_With_CPack). Concretely this behaviour causes the following problems:

* older versions of Sepiola do not get properly deinstalled during an update on Windows (since the registry key for the uninstaller is versioned)
* a cronjob/scheduler entry still points to the older version and does not get updated

TODO is the following:

* figure out where the respective CPack variables are used and whether it is safe to change them, see also the [NSIS documentation](http://nsis.sourceforge.net/Add_uninstall_information_to_Add/Remove_Programs)
* decide how to cleanup current entries. It probably makes sense to first fix the issue and release a 2.3.2 with the fix to make sure fresh installations do not suffer the same problems and document it first. And then release a 2.3.3 with an installer which actually does the cleanup

**Comment by dev-zero** [comment]
leaving this bug open since we still may want to find a way to cleanup old sepiola versions in the new installer.

**Comment by dev-zero** [comment]
Idea: write a (powershell) script which greps the list of installed applications for old (versioned) Sepiola installations and uninstalls each one of them.

**Comment by paescuj** [comment]
Closing this since it is not worth the effort.
