### ISSUE TITLE
Quota information should be updated regularly

### ISSUE THREAD

**Issue by meichenberger** [stepping-stone/sepiola#46]
The quota information on the overview screen should be updated regularly. Polling rate should be every 10 minutes as this corresponds with the cronjob on the backup server:

```
# Write quota values every 10 minutes
*/10 * * * * /usr/libexec/backup-utils/checkBackups.pl --quota | logger -t checkBackups.pl
```

**Comment by dev-zero** [comment]
This is actually a duplicate of issue #31
