### ISSUE TITLE
Ensure isolation of Cygwin installation required for rsync

### ISSUE THREAD

**Issue by dev-zero** [stepping-stone/sepiola#47]
Since we are going to use a Cygwin-based rsync to solve issue #45 we have to make sure that the Cygwin environment deployed with rsync is properly isolated from an already installed Cygwin.

This involves:
- use only the Cygwin dlls installed by us
- ignore any environment variables set by the user which would otherwise influence the Cygwin environment
- ignore any configuration file (other than the ones we deploy) present in Cygwin system- or user-directories

Cygwin should be installed alongside rsync in the Sepiola program directory (or a subdirectory).

**Comment by dev-zero** [comment]
Following the [Cygwin FAQ](https://cygwin.com/faq/faq.html#faq.using.third-party.multiple-copies) it seems that we can simply deploy the DLLs along with the executables and they should take precedence over an already installed Cygwin environment.

Reading [Environment Variables](https://cygwin.com/cygwin-ug-net/setup-env.html) and [The CYGWIN environment variable](https://cygwin.com/cygwin-ug-net/using-cygwinenv.html) I would suggest that we filter the `CYGWIN` environment variable (probably using the [`setProcessEnvironment`](http://doc.qt.io/qt-5/qprocess.html#setProcessEnvironment) method in the `ExtendedQProcess` and extending the `Process` class by a member variable `filteredEnvVars` which can be updated by an implementation of it)

**Comment by philippoehler** [comment]
When we write a new class for the ssh process (instead of plink), we should filter the CYGWIN environment variable as well.

**Comment by dev-zero** [comment]
ok, verified by code-review since we do not have a test case for this (would require a unittest for this class)
