### ISSUE TITLE
Move the .ssh folder to the .sepiola folder

### ISSUE THREAD

**Issue by philippoehler** [stepping-stone/sepiola#54]
In order to prevent unwanted manipulation on the ssh files (known_hosts and config) , we should move the .ssh folder to the .sepiola folder. 
This should also work with an other .ssh folder located in the Users home (User/USERNAME/).

**Comment by philippoehler** [comment]
fixed with commit 928a0e6409d5f6758d388f5e861962bc2caf8078
and commit 3d4986f2dd991aa1bb59f7533f32e8ba41b702fd

**Comment by philippoehler** [comment]
We should do this for Unix systems as well.

**Comment by philippoehler** [comment]
Reopened this issue for testing purposes

**Comment by dev-zero** [comment]
ok now, verified with sepiola-2.3.5-23-g1243b77-win64.exe
