### ISSUE TITLE
Scheduled Backup cannot be created if not (run as) admin

### ISSUE THREAD

**Issue by patklaey** [stepping-stone/sepiola#7]
When scheduling a backup, after test login to the server and password dialog box, an error message appears saying that the task could not be created (see screenshot). The problem is the new Vista feature "UAC" (User Access Control, see http://www.petri.co.il/disable_uac_in_windows_vista.htm), preventing calling schtaks, even conducted by a user within the "Administrators" group. If this feature is turned off, scheduling backup jobs work as expected. So a further authentication as "Administrator" is neccessary or at least a hint when UAC is turned on should be given to the user that he should running Sepiola with "real" Administrator privileges (by shift+right-clicking the Sepiola icon and selecting "run as administrator") for scheduling a backup.

Same behaviour on Windows XP, 7 and Windows Server 2008. 
![schedule_error](https://f.cloud.github.com/assets/2681963/1156842/87198e2a-1f93-11e3-8355-6bbf86883262.png)

(This bug is ported from https://sourceforge.net/p/sepiola/bugs/39/)

**Comment by paescuj** [comment]
Closing this since it doesn't seems to be the case any more.
