### ISSUE TITLE
Update bundled rsync and ssh for Linux

### ISSUE THREAD

**Issue by dev-zero** [stepping-stone/sepiola#75]
We updated rsync (and ssh) for Windows, now we have to do the same for Linux.
Documentation for that seems to be missing and should be created in the process, as preparation for issue #74

**Comment by dev-zero** [comment]
We will be using `LD_LIBRARY_PATH` when starting the `rsync` process for now, and can therefore copy in `rsync` and `ssh` as shared linked executables, together with the required library.

**Comment by dev-zero** [comment]
`rsync` could be taken from the build host (together with its binaries), `ssh` although is linked against Kerberos on Fedora, which is why we have to build it ourselves.

**Comment by dev-zero** [comment]
32bit-variants of `rsync` and `ssh` must be built manually

**Comment by dev-zero** [comment]
autoconf and automake support out-of-tree building:

```
tar xf rsync-3.1.2.tar.gz
mkdir -p rsync-3.1.2/build.x86_64
cd rsync-3.1.2/build.x86_64
../configure
make -j

tar xf rsync-3.1.2.tar.gz
mkdir -p rsync-3.1.2/build.{x86_64,i386}
cd rsync-3.1.2/build.x86_64
../configure
make -j

cd ../build.i386
../configure --host=i686-linux-gnu CFLAGS="-m32" CXXFLAGS="-m32" LDFLAGS="-m32"
```

**Comment by dev-zero** [comment]
the only library we probably must bundle, is `libcrypto.so`, all others should exist on almost all sane Linux OS (and have stable API and ABI).

**Comment by dev-zero** [comment]
see issue #47 for environment handling with QProcess (for setting `LD_LIBRARY_PATH`)

**Comment by philippoehler** [comment]
I built rsync on the jenkins server as described above. Then I replaced the old rsync executable inside the `/sepiola/tools/linux-x86_64` folder by the lates one (3.1.2) and ran a backup.  SSH is still the old version.
It seams that an additional package `openssh-askpass` is needed. 
Error log:
`rsync exited with exitCode 255 (ssh_askpass: exec(/usr/local/libexec/ssh-askpass): No such file or directory
Host key verification failed.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at /home/bbv-poe/rsync-3.1.2/build.x86_64/../io.c(226) [sender=3.1.2]
 ).`

**Comment by philippoehler** [comment]
To build the openssh executable on the build-server, there are additional headers required:
`configure: error: *** OpenSSL headers missing - please install first or check config.log ***`

For testing purposes,I solved this by installing `openssl-devel` on my local fedora.

**Comment by dev-zero** [comment]
ok, verified with sepiola-2.3.5-23-g1243b77-Linux-x86_64
