### ISSUE TITLE
Restore directly to a drive fails with "the source and destination cannot both be remote"

### ISSUE THREAD

**Issue by dev-zero** [stepping-stone/sepiola#77]
When selecting a Windows drive like `C:\` as the point to do a restore (whether _Restore to custom location_ or _Restore to original location_) I get the error:

```
rsync exited with with exitCode 1 (The source and destination cannot both be remote.
rsync error: syntax or usage error (code 1) at main.c(1261) [Receiver=3.1.1]
 ).
```

**Comment by dev-zero** [comment]
I guess that the path mangling from Windows to Cygwin paths fails when converting "C:\" to a Cygwin path.

**Comment by philippoehler** [comment]
When selecting the Windows drive `C:\` as the point to restore, I can not access to the restored folder `C`
![image](https://cloud.githubusercontent.com/assets/17530454/20930780/078bd1a0-bbcf-11e6-82b9-d4dc1e998c0b.png)

**Comment by dev-zero** [comment]
ok now, verified with sepiola-2.3.5-23-g1243b77-win64.exe
