### ISSUE TITLE
ACLs on Windows are taken from original path instead of the snapshot

### ISSUE THREAD

**Issue by dev-zero** [stepping-stone/sepiola#90]
When creating a backup, the `set_acl` tool is called with the original file paths instead of the path leading into the snapshot, see https://github.com/stepping-stone/sepiola/blob/develop/src/model/backup_thread.cc#L178
This may case inconsistencies and/or file-vanished errors.

**Comment by philippoehler** [comment]
It looks like that the old version of setacl.exe (2.0.3.0) is basicly  able to handle UNC paths leading into the snapshot `\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy16\Users\USER\Documents\syncMe.txt` .

**Comment by philippoehler** [comment]
But there are some difficulties.
Each backup creates a shadow Copy (HVSC) for each drive. The number of the HVSC is counting up and the drive information get lost. This means, that the acl data are unusable for a restore.

**Comment by dev-zero** [comment]
but at the time of reading the ACL we have the mapping from `\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopyNN` to whatever drive this Shadow Copy was taken from and can therefore rewrite the metadata from \\?\GLOBALROOT\Device\HarddiskVolumeShadowCopyNN` to `X:\` before uploading?

**Comment by dev-zero** [comment]
confirmed to be fixed in 2.5.0.rc0 by code-review
