### ISSUE TITLE
Rsync exit with error code 1 when selecting entire drive on Windows

### ISSUE THREAD

**Issue by dev-zero** [stepping-stone/sepiola#95]
When selecting an entire drive to backup on Windows, rsync will exit with error code 1 without transferring anything. This could possibly be the problem of accessing the root of a GLOBALROOT/Device, as mentioned in https://github.com/stepping-stone/sepiola/issues/45#issuecomment-215115380

**Comment by dev-zero** [comment]
This can be worked around by explicitly selecting only subfolders of a drive (caution: not the same as removing a subfolder after selecting the drive)

**Comment by philippoehler** [comment]
In Cygwin, I was able  to `ls`  into the shadow copy without specify a subdirectory: 
`$ ls -l /proc/sys/Device/HarddiskVolumeShadowCopy9/`

But when using a UNC path I wasn't able to `ls ` into the shadow copy without specify a subdirectory:
`$ ls -l //?/GLOBALROOT/Device/HarddiskVolumeShadowCopy9/
ls: cannot open directory '//?/GLOBALROOT/Device/HarddiskVolumeShadowCopy9/': Invalid argument
`

Using a UNC path and a subdirectory works:
`$ ls -l //?/GLOBALROOT/Device/HarddiskVolumeShadowCopy9/Users/
`

**Comment by dev-zero** [comment]
Ok, then it must be something else since we pass cygwin-paths to rsync and not UNCs for shadows, right?

**Comment by philippoehler** [comment]
Yes, we pass cygwin-paths to rsync. But it seams that rsync itself isn't able to handle the whole shadow copy as source path.

**Comment by philippoehler** [comment]
added a link to the shadow copy to backup the entire volume.

**Comment by dev-zero** [comment]
confirmed to be fixed in 2.5.0.rc0
